-- drop views
-- example "DROP VIEW IF EXISTS vw_invest_certificates;"

--drop tables
DROP TABLE IF EXISTS UserProfile CASCADE;
DROP TABLE IF EXISTS Rates;
DROP TABLE IF EXISTS Farm CASCADE;
DROP TABLE IF EXISTS Coffee CASCADE;
DROP TABLE IF EXISTS Roastery CASCADE;
DROP TABLE IF EXISTS Vendor CASCADE;
DROP TABLE IF EXISTS Sells CASCADE;


